// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVStWmj7--7qCrVSXPoDg_l552GGOyk4',
    appId: '1:701607183306:web:db126b45d7abeb50f88533',
    messagingSenderId: '701607183306',
    projectId: 'chat-app-f6052',
    authDomain: 'chat-app-f6052.firebaseapp.com',
    storageBucket: 'chat-app-f6052.appspot.com',
    measurementId: 'G-RVH1ZFK6M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-QeIPcOLkxJcilqV8so3CRZ4bU0buno',
    appId: '1:701607183306:android:5e1a8fe0c686b1d4f88533',
    messagingSenderId: '701607183306',
    projectId: 'chat-app-f6052',
    storageBucket: 'chat-app-f6052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ARbtANGHR5vAmRtM9zuCJVV-vGq9FgM',
    appId: '1:701607183306:ios:d8e88b3cee80d8f5f88533',
    messagingSenderId: '701607183306',
    projectId: 'chat-app-f6052',
    storageBucket: 'chat-app-f6052.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
